kind: Service
apiVersion: v1
metadata:
  name: gradio-rag-milvus-vllm-openai
  labels:
    app: gradio-rag-milvus-vllm-openai
spec:
  clusterIP: None
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 7860
      targetPort: http
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: gradio-rag-milvus-vllm-openai
